### PR TITLE
Makes the ES subnet input an array so it can receive more than one subnet

### PR DESCRIPTION
**Pull request by lortega**
I was getting an error when trying to create the ES for more than one subnet. 

I changed the string for an array and it worked.

### CODE REVIEW

**Comment by egarbi** [comment]
@lortega Thanks for this, Agree that subnets need to be an array.
But instead a `split` I would update the type of the variable in the module to `list`.
I've just tested my stuff and after the change, it works well.
I will update the module for you to check.

**Comment by egarbi** [comment]
@lortega take a look on this one:
https://github.com/egarbi/terraform-aws-es-cluster/pull/2

**Comment by lortega** [comment]
I'll close this one then. But it could be useful to have some outputs though...

**Comment by egarbi** [comment]
Output Agregado. Gracias !!

**Pull request closed without merging**
